version: 2.1

orbs:
    mirci: libmir/upload_docs@0.0.0

jobs:
    build:
        docker:
        - image: libmir/circle-dlang
        steps:
        - checkout
        - run: cp -r /repo/* ./  && cat meson.build.1 >> meson.build
        - run: meson build --default-library=static -D with_test=true -D with_doc=true
        - run: ninja -C build test -j1
        - run: cp -r build/web ./
        - mirci/persist_docs:
            from: web

workflows:
    version: 2
    build-deploy:
        jobs:
        - build:
            filters:
                tags:
                    only: /^v(\d)+(\.(\d)+)+$/
        - mirci/upload_docs_job:
            from: web
            to: mir-algorithm.libmir.org
            requires:
            - build
            filters:
                branches:
                    only: master
                tags:
                    only: /^v(\d)+(\.(\d)+)+$/
